apiVersion: apps/v1
kind: Deployment
metadata:
  name: expo-outlook-bookinghandler
  labels:
    app: expo-outlook-bookinghandler
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: expo-outlook-bookinghandler
  template:
    metadata:
      labels:
        app: expo-outlook-bookinghandler
    spec:
      securityContext: # Container is build with non-root "appuser"
        fsGroup: 101 # Makes sure the app can write to the mounted volumes
      containers:
        - image: ghcr.io/teknikens-hus/expo-outlook-bookinghandler:latest
          name: expo-outlook-bookinghandler
          env:
            - name: TZ
              value: "Europe/Stockholm"
            - name: Interval
              value: "1800"
            - name: EXPO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: expo-outlook-bookinghandler-secret
                  key: expo_token
            - name: EXPO_URL
              value: "https://booking.yourdomain.com"
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: expo-outlook-bookinghandler-secret
                  key: smtp_password
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: expo-outlook-bookinghandler-secret
                  key: smtp_username
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: expo-outlook-bookinghandler-secret
                  key: smtp_host
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: expo-outlook-bookinghandler-secret
                  key: smtp_port
          # Adjust the resource limits as needed
          resources:
            requests:
              memory: "20Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "20m"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: config-volume
          configMap:
            name: config-configmap
        - name: data-volume
          persistentVolumeClaim:
            claimName: expo-outlook-bookinghandler-pvc