apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
metadata:
  name: kustomize-expo-outlook-bookinghandler
resources:
- deployment.yaml
configMapGenerator:
  - name: config-configmap
    files:
      - config.yaml=config.yaml
    options:
      disableNameSuffixHash: false